dist: trusty
language: python
python:
  - "3.6"
before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - "pip install -U coverage flake8 'isort<4.3.5' pylint pytest pytest-cov pytest-mock sphinx sphinxcontrib-asyncio"
  - "pip install -U -r requirements/base.txt"
script:
  - "pytest -vs --cov=jishaku --cov-report term-missing:skip-covered"
  - "flake8 ."
  - "pylint -j '$(nproc)' jishaku"
  - "isort . --check-only --recursive"
  - "python ./setup.py sdist bdist_egg bdist_wheel"
  - "cd docs && make html"
