dist: trusty
language: python
python:
  - "3.6"
  - "3.7"
before_script:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - "pip install -U $(find requirements -name *.txt -print | sed -e 's/^/-r /' | tr '\n' ' ')"
  - "pip install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice] git+https://github.com/PyCQA/astroid"
script:
  - "pytest -vs --cov=jishaku --cov-report term-missing:skip-covered"
  - "flake8 ."
  - "pylint jishaku"
  - "isort . --check-only --recursive"
  - "python ./setup.py sdist bdist_egg bdist_wheel"
  - "cd docs && make html"
